### ISSUE TITLE
Add some more additional basic questions.

### ISSUE THREAD

**Issue by snehitvaddi** [infermedica/symptom-checker-chatbot-example#2]
Your API is good and flawless, but I suggest you add some more basic questions like
* Do you have diabetes. 
* How is your blood pressure. etc.
I have shown this to a doctor and he told without basic knowledge like the above questions it is not good to treat a patient. 
<br>I hope you take this as an input.👍

**Comment by adam-ra** [comment]
Thanks for this feedback! Good points, indeed knowing basic risk factors is important to be better informed about the patient's condition.

Some of these questions may already be asked by the API. For instance, you'll get a question whether you have been diagnosed with diabetes if the engine finds this question important for differential diagnosis. Similarly, there's a question about hypertension that sometimes gets asked. So, in principle, this should suffice unless the reported evidence is very unspecific and some exotic condition requires knowledge about a risk factor to be suspected at all.

Also, some of our apps use a fixed risk factor poll at the beginning. Here it's not so easy because it's supposed to be voice-friendly, so we prefer to have the engine (behind the /diagnosis API) decide if risk factor questions are needed and ask them only if very relevant in the particular case (not to make the interview too long). This is done on symptomate.com, for example — there's the screen with check boxes for things such as injury, hypertension. The choice of risk factors may be tailored to the domain and expected patient profile. The list of all available risk factors may be obtained from this endpoint: https://developer.infermedica.com/docs/medical-concepts#risk-factors

I've notified our engine team that it would be helpful to have a more convenient way of getting recommended risk factors from the API for a given patient age and sex.

Again, thanks for the feedback! I'm closing this issue here as it's not directly related to this chatbot example but rather to the API.

**Comment by adam-ra** [comment]
The list of common useful risk factor is also available here: https://developer.infermedica.com/docs/diagnosis#common-risk-factors
